### PR TITLE
Fix API: Disable CSRF attacks protection

### PR DESCRIPTION
**Pull request by richardtop**
@jgorset, I've disabled forgery protection in order to make PUT/POST requests work correctly.

### CODE REVIEW

**Comment by timkurvers** [comment]
What is the authentication scheme in use here?

**Comment by richardtop** [comment]
None

**Comment by jgorset** [comment]
Note that this doesn't actually disable CSRF protection, but rather logs you out for any requests that don't have it. I guess that works, though, since we don't really have authentication at all. :smile:

**Comment by jgorset** [comment]
Thanks @richardoti! :cake:

**Comment by timkurvers** [comment]
:+1:

**Comment by richardtop** [comment]
@jgorset I just used suggestion from the comment and it worked :smile: 

``` Ruby
   # Prevent CSRF attacks by raising an exception.
   # For APIs, you may want to use :null_session instead.
```

**Pull request merged**
