### PR TITLE
Fix err 500 when deleting room

### PR DESCRIPTION
**Pull request by richardtop**
@jgorset, server was returning 500 when trying to delete room because there were no cascade rule to delete all topics and DB transaction failed.

I've added cascade rule to make deletion work.

### CODE REVIEW

**Comment by timkurvers** [comment]
:+1:

Be careful when using `delete_all` as it does not [execute any ActiveRecord lifecycle hooks](http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#module-ActiveRecord::Associations::ClassMethods-label-Delete+or+destroy-3F). Use `destroy_all` instead. There's also a newer symbol syntax that can be used since Ruby 1.9:

``` ruby
has_many :topics, dependent: :destroy_all
```

**Comment by richardtop** [comment]
Hmm, interesting. But should those hooks be executed? I will do as you suggested for now, but what this code actually does is deleting all the topics before deleting room.
It will send tons of messages via Pusher, rather than sending one "RoomHasBeenDeleted" message.

**Comment by timkurvers** [comment]
Ah! Where are these hooked in, I can't seem to find them.

**Comment by richardtop** [comment]
https://github.com/jgorset/lean-coffee/blob/master/app/controllers/topics_controller.rb

If I understand this code correctly, if using `destroy_all` messages would be sent for each topic:

``` Ruby
  def destroy
    @topic = @room.topics.find params[:id]
    if @topic.destroy
      push_updated_topic @topic
      head :no_content
    end
  end
```

While there is no need in such messages, as the client should redirect user to main page instead (room is deleted) or show message.

**Comment by timkurvers** [comment]
No this is controller-code only, executed when destroying a topic through the API. The hooks could be defined on the model. In this case there don't seem to be any, but if someone were to add them later using `delete_all` could cause issues.

**Comment by richardtop** [comment]
Allright, then I will also add custom Pusher notification, to make at least iOS get know about room deletion/creation/update as well.

Thanks for a good catch :smile:

**Comment by richardtop** [comment]
@timkurvers I got this error:
screen shot 2015-10-02 at 17 53 12
But after I've changed to `has_many :topics, dependent: :destroy` everything worked fine. Didn't check the DB status, though.

**Comment by timkurvers** [comment]
My bad, the option is called `:destroy` :+1:.

For some reason Rails' API is inconsistent here having `Model.destroy_all` and `Model.delete_all`, but the `:dependent`-option for a `has_many`-relation doesn't accept `:destroy_all`.

**Comment by richardtop** [comment]
The only thing I concern is whether `destroy` does cascade delete. But as I don't get any inconsistency errors from the DB and all transactions succeed, it seems to be fine.

Now I'm finishing adding PUSH-commands to make clients able to reload room list.

**Comment by timkurvers** [comment]
It should. When using `:delete_all` it definitely will not.

**Comment by richardtop** [comment]
Now I've added notification, so, at least iOS client should perform updates.

**Comment by jgorset** [comment]
Neat, thanks @richardoti!

**Comment by timkurvers** [comment]
:+1:

**Pull request merged**
